In [2]:
import numpy as np

In [8]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
x = np.arange(9).reshape(3,3)
print(x)
print(x < 10)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [20]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(array1)
odd = array1[array1%2!=0]
print("Odd numbers are", odd)
array1[array1%2!=0] = -1
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]
Odd numbers are [1 3 5 7 9]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [25]:
array1D = np.array([1,2,3,4,5,6,7,8,9,10])
array2D = array1D.reshape(2,5)
print(array1D)
print(array2D)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [46]:
a = np.arange(25,34).reshape(3,3)
b = np.arange(34,43).reshape(3,3)
print(a)
print(b)
v = np.vstack((a,b))
print(v)
d = np.dot(a,b)
print(d)
s = np.sum(d)
print(s)

[[25 26 27]
 [28 29 30]
 [31 32 33]]
[[34 35 36]
 [37 38 39]
 [40 41 42]]
[[25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]]
[[2892 2970 3048]
 [3225 3312 3399]
 [3558 3654 3750]]
29808
