In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
print(a)
print(b)
B = np.delete(b,[0,1])
print(a)
print(B)
c = a[2: ]
d = B[ :2]
print(c, d)
e = np.sum(c)
print(e)
f = np.sum(d)
print(f)
print(e + f)

[1 2 3 4 5]
[4 5 6 7 8 9]
[1 2 3 4 5]
[6 7 8 9]
[3 4 5] [6 7]
12
13
25


In [9]:
a = np.array([1,1,1])
b = np.array([2,2,2])
c = np.array([3,3,3])
d = np.array([1,2,3])
e = np.concatenate((a,b,c,d,d,d),axis=0)
print(e)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
